# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-06 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_subscribe_to_updates_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betatestapplication',
            name='project_description',
            field=models.TextField(blank=True, help_text='What are you going to use the instance for? Do you have any specific requirements?', verbose_name='your project & requirements'),
        ),
    ]
